### PR TITLE
Fix "unexpected token c at position X" error when app insights trace gets too large

### PR DESCRIPTION
**Pull request by trittimo**
I took a stab at fixing this bug and so far have seen no adverse issues from myself or any coworkers after running it for a few days.

If you haven't encountered this bug, it should be pretty trivial to reproduce. Just go play around with a policy for a while and generate as many app insights events as you can. The more data the better. Eventually when you go to refresh the app insights in VS code, you will get an "Unexpected token c at position X", which is a result of `JSON.parse` failing in ApplicationInsightsExplorerExplorerProvider.ts.

The fix for this was pretty trivial: just make the `body.replace('""', '"')` a last resort option instead of always trying to do it. I'm unclear why this replace exists in the first place.

The other change that I added was a try/catch for the `JSON.parse(data)` in the `getWebviewContent` function. I know it looks like I made a lot changes, but that's just because I moved the variables that go into the HTML to the top of the function.

### CODE REVIEW

**Comment by Norrch2** [comment]
@trittimo 

Perhaps this isn't a bug with the extension but a bug with Application Insights. For several months now I have been experiencing an issue with Application Insights and have got no traction. I'll show what you what I mean.

image

Here you can see that 2 of the 15 trace logs here don't start with the proper json. For example, line 1 starts with the proper json format [{"kind".... and line 2 just says "23",... 

Here is an example of a properly parsed application insights message 
image


And this is what it looks like when there was a problem parsing it. 
image


As you can see the message is entirely different and this may be what the users are experiencing. If so, this would be the wrong area to open an issue. However, my attempts to get this resolved with MS have been unfruitful. @yoelhor @JasSuri perhaps you can step it?

**Comment by Norrch2** [comment]
@trittimo perhaps you can verify my findings within your application insights and when you experiencing a parsing issue?

**Comment by trittimo** [comment]
@Norrch2 I think you're probably right, they seem to be splitting the JSON object up across multiple app insights "rows" (probably not the correct term) when it gets to a certain size. I see the same thing in my app insights instance.

If that is the intended behavior, which it very well may be, it may be possible to join those together so we get a valid JSON object on the extension side. The unfortunate thing about it is that there doesn't seem to be any property on the app insights object returned by the API call which would indicate how to join these objects back up, especially since the granularity of the timestamps isn't accurate enough for us to do that by hand.

It would still be fantastic if we could get this merged into the extension though as ultimately it's just a few try/catch blocks and I don't see this getting changed on the Microsoft side any time soon. I seem to encounter this bug on a pretty much weekly basis and it definitely is a headache for debugging :(

**Comment by JasSuri** [comment]
This is due to AAD B2C trying to overcome the App Insights row size limit. We saw truncation in customers logs and essentially split the log over multiple rows if it was too large. That is why you are seeing the invalid JSON, they need to be merged. We need to handle this scenario in the extension if possible.

**Comment by yoelhor** [comment]
Thanks for the fix. I have reproduced this issue and applied the fix. Looks good to me. The new version `1.2.104` is published. Please check the new version and keep me posted. Again I would like to take this opportunity and thank you for all you have done. Yoel

**Comment by trittimo** [comment]
Much appreciated Yoel! Glad I was able to contribute. This is by far the most useful VS Code extension I have 🙂

**Pull request merged**
