### PR TITLE
Added the ability for xml files to be in nested folders

### PR DESCRIPTION
**Pull request by Norrch2**
Added the ability for the b2c extension to do policies in nested folders and have the same output.

### CODE REVIEW

**Comment by BradCandell** [comment]
Great job implementing this! I'd love for this to get merged in and part of the production build! Just saved me from having to do the same thing!

**Comment by BradCandell** [comment]
@yoelhor or @rbinrais - It would be awesome to get a few more active contributors on this extension, if possible. This PR is an excellent addition, and I would like to submit a PR after this gets merged in. 

Is this a community-run repo that I might be able to contribute to? 

Not sure how else to reach out to the Repository owners.

**Comment by Norrch2** [comment]
Agreed. This is confusing, the repo specifically states that this is a community ran effort but it doesn't appear that anyone can do anything with it. The last update to this was 4 months ago and we all know that @yoelhor has a lot of things to do already.

**Comment by BradCandell** [comment]
Perhaps @JasSuri could help us figure out the best way to support this Community-driven extension. I've got some changes that I would like to make too, but am holding off until there is a clear indicator that such work is worthwhile.

**Comment by Norrch2** [comment]
@BradCandell perhaps it would be best to fork it and continue developing it as the "unofficial" version?

**Comment by BradCandell** [comment]
> @BradCandell perhaps it would be best to fork it and continue developing it as the "unofficial" version?

I'm in, if you are! Maybe we give them a couple more weeks to advise us on how best to see this extension get its updates. If not, we fork and start our own?

**Pull request merged**
